# Generated by Django 6.0.7 on 2026-08-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_cotizacion_cliente_telefono_cotizacion_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecioProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_negocio', models.CharField(help_text='Ej. Honda Central, AutoZone Sur, Refaccionaria El Pistón', max_length=150)),
                ('codigo_refaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_refaccion', models.CharField(max_length=200)),
                ('precio_referencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefono_contacto', models.CharField(blank=True, max_length=30, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Permite pausar o reactivar el producto en el POS sin borrar su historial'),
        ),
    ]
