# Generated by Django 6.0.7 on 2026-08-19 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_listaprecioproveedor_producto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Descuento Mostrador, Amigo Mecánico', max_length=50)),
                ('porcentaje', models.IntegerField(help_text='Porcentaje entero: 2, 5, 8, 10, 15...')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['porcentaje'],
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('total_cobrado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('num_ventas', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='corte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_incluidas', to='sistema.cortecaja'),
        ),
    ]
