# Generated by Django 6.0.7 on 2026-08-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_descuentoconfig_cotizacion_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20, null=True),
        ),
    ]
